export CUDA_VISIBLE_DEVICES=0,1

DATE=$(date '+%Y-%m-%d-%H-%M-%S')

python3 -m verl.trainer.main_ppo \
    data.train_files=data/literature_screening/base/train.parquet \
    data.val_files=data/literature_screening/base/test.parquet \
    data.train_batch_size=128 \
    data.val_batch_size=128 \
    data.max_prompt_length=2500 \
    data.max_response_length=1536 \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.strategy=fsdp \
    actor_rollout_ref.rollout.temperature=0.6 \
    actor_rollout_ref.actor.ppo_mini_batch_size=128 \
    actor_rollout_ref.actor.ppo_micro_batch_size=4 \
    actor_rollout_ref.rollout.log_prob_micro_batch_size=2 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.4 \
    actor_rollout_ref.ref.log_prob_micro_batch_size=2 \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    critic.model.enable_gradient_checkpointing=True \
    critic.optim.lr=1e-5 \
    critic.ppo_micro_batch_size=4 \
    critic.model.enable_gradient_checkpointing=True \
    algorithm.kl_ctrl.kl_coef=0.001 \
    trainer.logger=['wandb'] \
    +trainer.val_before_train=False \
    trainer.default_hdfs_dir=null \
    trainer.n_gpus_per_node=2 \
    trainer.nnodes=1 \
    trainer.save_freq=100 \
    trainer.test_freq=600 \
    trainer.project_name=literature_screening \
    trainer.experiment_name=literature_screening_3b \
    trainer.default_local_dir=/shared/eng/pj20/lmr_model/literature_screening_3b_new \
    actor_rollout_ref.model.path=Qwen/Qwen2.5-3B-Instruct \
    critic.model.path=Qwen/Qwen2.5-3B-Instruct \
    trainer.total_epochs=5 2>&1 | tee exp_log/3b-ppo-verl_demo_$DATE.log
