export CUDA_VISIBLE_DEVICES=0,1
export WANDB_API_KEY="306617ef72f115b128196d10542fe8942f33a63e"
# export HF_HOME="/srv/local/data/linjc/hub"

DATE=$(date '+%Y-%m-%d-%H-%M-%S')

python3 -m verl.trainer.main_ppo \
    data.train_files=data/literature_mining/base/train.parquet \
    data.val_files=data/literature_mining/base/test.parquet \
    data.train_batch_size=64 \
    data.val_batch_size=64 \
    data.max_prompt_length=500 \
    data.max_response_length=500 \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.strategy=fsdp \
    actor_rollout_ref.actor.ppo_mini_batch_size=16 \
    actor_rollout_ref.actor.ppo_micro_batch_size=8 \
    actor_rollout_ref.rollout.log_prob_micro_batch_size=2 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.2 \
    actor_rollout_ref.ref.log_prob_micro_batch_size=2 \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    critic.model.enable_gradient_checkpointing=True \
    critic.optim.lr=1e-5 \
    critic.ppo_micro_batch_size=8 \
    critic.model.enable_gradient_checkpointing=True \
    algorithm.kl_ctrl.kl_coef=0.001 \
    trainer.logger=['wandb'] \
    +trainer.val_before_train=False \
    trainer.default_hdfs_dir=null \
    trainer.n_gpus_per_node=2 \
    trainer.nnodes=1 \
    trainer.save_freq=50 \
    trainer.test_freq=200 \
    trainer.project_name=literature_search \
    trainer.experiment_name=literature_search_3b_continue \
    trainer.default_local_dir=/shared/eng/pj20/lmr_model/literature_search_3b \
    actor_rollout_ref.model.path=/shared/eng/pj20/lmr_model/literature_search_3b/actor/global_step_100 \
    critic.model.path=/shared/eng/pj20/lmr_model/literature_search_3b/critic/global_step_100 \
    trainer.total_epochs=15 2>&1 | tee exp_log/3b-ppo-verl_demo_$DATE.log
